on: issue_comment

env:
  DAGGER_VERSION: 0.18.18

jobs:
  handle:
    name: Handle event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run pipeline
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # v8.0.0
        with:
          verb: call
          args: handle --name $GITHUB_EVENT_NAME --event $GITHUB_EVENT_PATH --token env:GITHUB_TOKEN
          version: ${{ env.DAGGER_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
