name: Octoslash

on: issue_comment

permissions:
  issues: write
  pull-requests: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - run: go install github.com/sagikazarmark/octoslash/cmd/octoslash@workflow-run

      - name: Run octoslash
        run: octoslash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
