on: workflow_dispatch

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - run: echo "Hello, World!" > hello

      - run: |
          git add .
          git commit -m "Add hello file"

      - run: git push origin ${{ github.ref_name }}
