on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo "Hello, World!" > hello

      - name: Update PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref_name }}
